{
'name': 'Assurfaz',
'version' : '1.1',
'sequence': '1',
'description': 'gestion pour les compagnies d’assurance et courtiers en assurance',
'category': 'Services',
'website': 'https://www.digifaz.com',
'author': 'DIGIFAZ',
'depends': ['base'],
'data': ['security/assurfaz_security.xml',
'security/ir.model.access.csv',
'views/menu.xml',
'views/assurance_auto_vehicule_view.xml',
'views/assurance_auto_garantie_view.xml',
'views/assurance_auto_view.xml',
],
'installable': True,
'application': True,
'auto_install': False,
'license': 'LGPL-3',
}