{
'name': 'Assurfaz',
'version' : '1.1',
'sequence': '1',
'description': 'gestion pour les compagnies d’assurance et courtiers en assurance',
'category': 'Services',
'website': 'https://www.digifaz.com',
'author': 'DIGIFAZ',
'depends': ['base','crm','stock','account','sale_management'],
'data': ['security/assurfaz_security.xml',
'security/ir.model.access.csv',
'views/menu.xml',
'views/assurance_auto_vehicule_view.xml',
'views/assurance_auto_garantie_view.xml',
'views/assurance_auto_view.xml',
'views/marque_vehicule_view.xml',
'views/modele_marque_vehicule_view.xml',
'views/prime_view.xml',
'views/sinistre_view.xml',
'views/assurance_voyage_view.xml',
'views/assurance_habitation_view.xml',
'views/assurance_sante_view.xml',
'views/assurance_vie_view.xml',
'views/tableau_bord_crm_view.xml',
'views/tableau_bord_stock_view.xml',
'views/tableau_bord_sinistre_view.xml',
'views/tableau_bord_prime_view.xml',
'views/res_partner.xml'
],
'installable': True,
'application': True,
'auto_install': False,
'license': 'LGPL-3',
}
