from . import assurfaz
from . import vehicule
from . import marque_vehicule
from . import modele_marque_vehicule
from . import garantie
from . import assurance_auto
from . import crm
from . import stock
from . import prime
from . import sinistre
from . import assurance_habitation
from . import assurance_sante
from . import assurance_voyage
from . import assurance_vie
from . import vente
from . import facturation
from . import res_partner